sudo: false
language: node_js
node_js:
- "8"
before_install:
- npm install -g codecov
script:
- npm run lint
- npm run test
- npm run test:bs
after_success:
- codecov
after_failure:
- codecov
env:
  global:
  - secure: AGGHG4s9ByRl/z5tdsWr1YwL6gHtsEZdkgCPltVK441WT1BsLueloZaFMSwPza8g6i27kFx9ho8qr1BVB66z2GyoEO0g36XZiQUeaCn6/k+Sgha5xhB2jVJppWeUEQFcMubS2sgUUeAnFwOmh7oszmxvmEk+3RqZFr+LvboX19NRdK0XyUw0XLz67jOUYFinXfDQPFkU5NhiEzKep2wkK2WLhehQgNW06w/HgJHrieowmf5KXg5oOfkYA5U7SIeZ6g9nySpaONfdDD5Pls3GFf64tw75w4vEvJurpVNwm48nS7PGJsu4lcrDMOo2/1PdWoE2m/U1ZaAsMldnuW+b6vaFgbtVGYpN1Yq6TRZUKJrM487WaFceJOBLlbQtVwCkypeAOKxkMsIrjwNtP5Vj8KFwhnT4vnG4aTNmioUQp2qeHawo8TVBMRzUPduubhKlu/+9HathastlGDJGWAd1h3UcbCos6Pqe3N85dbQhoElnNTJ8cc9AUJGf6sczYgpLRSqR2KohxbWLlxfz5lQKj3bZCyzTzyljAxP3OPzXrN+iqG3xY0Ta/ELGocY6xAR0tojqqa6JIdXcYuP/489S2QnPvhywKYL0gEiAzTZtlYVnn45PCEaaVQg2Q4KR6HrfRBPKGFUS22USucME+8RH3WpsBtA3OkZ13ATb6buOaX0=
  - secure: b7HG4JK4Oxs8kmhc2vJXlrWfztg0T0RGTT13zHk5gR5XHARehp7ZAHudO+yUDHqQcmcWKtm1QDkRfhaBIHAHODkBQOYN3L5b1btf6GZXT+GIt1LygosYyB4v/EYGq23zZ6iBRgyDiZYgXDJdykJru1m+XeYsw6ThXqIyLPz7APvrllBcMij09pLyH+V5Jk2QEwB/e37+Pdp6RoJs01mp9Dl7LpXdo/5EfopT2aoKgHjxhi5VF7TOIc5RQqe2OCO4W2DvsRZGlXq8b/+bBtdERCrpRgnv77JpdhP0bsa0BBZgWlqPuqdqb8lZGIw/QWKes8ad7TPFUCzAwCU4S1dWU5iHsEwbi74Fy4C/ppXWxxHhN8lnXWDpiwCjwtE1ixgockSgA2RXuWiRDTE3LIzJJJFnbqLU73915GV9C+vAS/Zfr3D8xkrXDsOABItnIFc0KAxJ3v3FXeZz1KyZJrfgro0PTHzcvGGjbaNC5zuC/PKkI0abMrrFrfw/KvDCdVB2T4SATjOaziGalZWRzERvrlxnSCIrf+gmxS6v6APhyPLJ6+dxWNZmnFg6uG3DzcbhIRWqy0nlHOom62spn0H/aYT/mZWL4gnTab5bWtdyjugFjc4b6CaanptEAFwWQfG4mg1RpyrFeNGerC7zG0L6tll+sjp+E/5rRCU1vq9YUtk=
deploy:
  provider: npm
  email: npm@t-code.pl
  skip_cleanup: true
  api_key:
    secure: OpnN89pc/DQH5Rmy1KCvyKmjrrbscI6Mg8QGkbnnZtTzXZ4n24nYW8MFf/YofzE9UZp//WTGckesDc5UgG3e6zQYY0WGfJsQbSxYPLH67YKDA5ke0Hf7QTPnYFCg5kXqDxESvhA1e9pZlrTh/ABJHHa0ODliUSrVhVEsZmYDzTdTAeAnlTMedqUoOSEK/9J0Xho6lYq2B1WGgKf8UZONojXb3S+vj5YEEwo/RM+m7aa5sQAKE/T5ntFfvF8/xXwzgCb1eNLIaXA5rp8iFs0VD1CJeL/He3U1xgAszVNj6tPk8H8K0BCzMZyXcxeS6l28O3XnjCx+IYW6pRqQ7nt35FNn+FBEkJ1jRcxaF5HYHd1usJoKt6V003+rTPNgsKilIVhx9h4ccztS2ZwKKYn0qypxIAteIJi2Yjv65PjJ7uAIsb2jSw2cXqgqLdbkOqqMqtRPb02wuxaHvFkQFfXDr4tJ/ANHHCxWa8un0fwGdl1cwobTe7E6HwrHkNgPwSQF33AdLCla5HtXTIMrZsVOv4+bqPQKkk11vEXUj542FYJ/oFUDIB05VGk7kIKlgi5tgDZrVQfOzwkQWoqfnoTblq2U5dm7t/grh6RIyT04PJxy6WNBF37ZFumgLcJzaSpNzAduGm6YN5Qz3zxHC/0HLPhJYuab7og8ClfuOtlDWq0=
  on:
    tags: true
    repo: hypermedia-app/hydrofoil-shell
